#!/bin/bash -f 
# PBS job options (name, compute nodes, job time)
#PBS -N Matpower 
#PBS -l select=1
#PBS -l walltime=00:20:00
#PBS -l place=excl
#PBS -A "z04"


# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)               
  
# Change to the directory that the job was submitted from
# (remember this should be on the /work filesystem)
cd $PBS_O_WORKDIR
./matpower
